# Generated by Django 3.2.2 on 2021-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Farm_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='Farmer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Manager_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Pass_book_no',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='Postal_code',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='Restaurant_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Restaurantarea',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Staff_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='State',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Village',
            field=models.CharField(default='', max_length=200),
        ),
    ]
